package constants

const DEPRECATED_DEBTOR_PHONE_MOBILE_TYPE_ID = 3
const DEPRECATED_DEBTOR_PROPERTY_PASSWORD_REGISTERD = "PASSWORD_REGISTERED"
const DEPRECATED_DEBTOR_PROPERTY_SECURITY_CODE = "SECURITY"
const DEPRECATED_DEBTOR_PROPERTY_PHONE_VALIDATION_CODE = "SMS_VALIDATION"
const DEPRECATED_DEBTOR_PROPERTY_EMAIL_VALIDATION_CODE = "EMAIL_VALIDATION"
const DEPRECATED_DEBTOR_PROPERTY_CANCELLED_ACCOUNT = "data.desativacao"
const DEPRECATED_DEBTOR_AUTHORITY_ADMIN = "ROLE_ADMIN"
const DEPRECATED_DEBTOR_AUTHORITY_USER = "ROLE_USER"

const DEPRECATED_DEBTOR_STATUS_ACTIVE = 1
const DEPRECATED_DEBTOR_PRINCIPAL = 1

const CUSTOMER_MIN_AGE_TO_DEFINE_MINOR = 18

const CUSTOMER_FIND_REDIRECT_SLUG = "reset_password"

const CUSTOMER_DEFAULT_ROLE_NAME = "user"
const CUSTOMER_ADMIN_ROLE_NAME = "admin"

const CUSTOMER_PHONE_STATUS_SLUG_NOT_CONFIRMED = "not_confirmed"
const CUSTOMER_PHONE_STATUS_SLUG_CONFIRMED = "confirmed"
const CUSTOMER_PHONE_STATUS_SLUG_ON_UPDATE = "on_update"

const CUSTOMER_EMAIL_STATUS_SLUG_NOT_CONFIRMED = "not_confirmed"
const CUSTOMER_EMAIL_STATUS_SLUG_CONFIRMED = "confirmed"
const CUSTOMER_EMAIL_STATUS_SLUG_QUESTIONABLE = "questionable"
const CUSTOMER_EMAIL_STATUS_SLUG_ON_UPDATE = "on_update"

const ORIGIN = "ac_novos_cadastros_prov"
